require: rubocop-rails
require: rubocop-performance

# AllCops:
#   EnabledByDefault: true

Layout/LineLength:
  Enabled: false
  Max: 154

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/ConstantResolution:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'


# rubocop-performance

Performance/AncestorsInclude:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true