version: '2'
services:
  db:
    image:  postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
        # fixes PG::ConnectionBad: could not translate host name "db" to address: Name does not resolve
        # allows connection without password
        POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    # image: nfigueroa/personal-finance:latest
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    # volumes:
    #   - /Users/nelson/Projects/personal_finance:/app