development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: test
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

production:
  adapter: postgresql
  database: production
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db
