# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: nelson
  password: nelson
