development: &default
  adapter: postgresql
  database: development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

test:
  <<: *default
  database: test

local:
  adapter: sqlite3
  database: db/local.sqlite3
  pool: 5
  timeout: 5000