development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production: &production
  adapter: postgresql
  database: development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

test:
  <<: *production
  database: test
